### PR TITLE
Revert "More tests"

### PR DESCRIPTION
**Pull request by RuairiK**
Reverts RuairiK/divesit.es#28

Travis build is failing due to something in the delete tests, rolling back while I investigate https://travis-ci.org/RuairiK/divesit.es/builds/60028903

### CODE REVIEW

**Comment by sdob** [comment]
Hmmm. Are you OK merging authentication into master?

**Comment by RuairiK** [comment]
Did you do it on your forked repo? If not, then no, as if that's not the problem merging now will only make it harder to debug the problem with this PR. This is going to master, but perhaps it's testing code in authentication which is not available in upstream master?

**Comment by sdob** [comment]
I'm on master, yes. I'm having an interesting problem here, though: npm test is working fine on my local machine but the Travis build is failing. Let me check this out.

**Comment by RuairiK** [comment]
In that case, I'll merge from authentication to master, I suspect that's the issue.

**Comment by RuairiK** [comment]
Never mind,  my master is up to date with the authentication changes, so that's not the issue...

**Comment by sdob** [comment]
I've just fixed a version mismatch by running npm install (should.js has updated) but I still can't nail down why exactly my mocha tests were passing on my machine and failing on Travis. As of [https://travis-ci.org/sdob/divesit.es/builds/60031595](this build) there's a difference in how the two interpret comparison for equality of Mongoose IDs. It's odd. My [https://travis-ci.org/sdob/divesit.es/builds/60032185](most recent) build is passing mocha and then failing a second pass to generate coverage data.

¯\_(ツ)_/¯

**Comment by sdob** [comment]
Based on the fact that my local machine and Travis run the unit tests in a different order (WTF, but I guess I should be expecting that by now), I suspect that not writing my teardown code in a sufficiently defensive manner might be causing a race condition.

On the other hand, I just re-ran [a previous build](https://travis-ci.org/sdob/divesit.es/builds/60031595) and this time npm install errored with a timeout.

And people use this in production.

**Pull request merged**
